name = "ai-image-gen"
main = "src/index.ts"
compatibility_date = "2025-04-28"
compatibility_flags = ["nodejs_compat"] # If you need Node.js compatibility features

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"

[observability.logs]
enabled = true

[r2_buckets]
IMAGE_BUCKET = { binding = "IMAGE_BUCKET" }
IMAGE_LOG = { binding = "IMAGE_STORE" }

 [[kv_namespaces]]
 binding = "IMAGE_STORE"
 id = "92b9d3bfb8994d92b2e750f630911824"
