name = "ai-image-gen"
main = "index.ts"
compatibility_date = "2025-04-28"

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "IMAGE_STORE"
id = "92b9d3bfb8994d92b2e750f630911824" }
