name = "ai-image-gen"
main = "src/index.ts"
compatibility_date = "2025-04-28"
compatibility_flags = ["nodejs_compat"] # If you need Node.js compatibility features

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "image-bucket"

[[durable_objects.bindings]]
name = "IMAGE_OBJECTS"
class_name = "ImageObject" # The name of your Durable Object class